package by.iodkowski.telegram.api.file

import org.drinkless.tdlib.TdApi

/**
  * Represents a local file.
  *
  * @param path                   Local path to the locally available file part; may be empty.
  * @param canBeDownloaded        True, if it is possible to try to download or generate the file.
  * @param canBeDeleted           True, if the file can be deleted.
  * @param isDownloadingActive    True, if the file is currently being downloaded (or a local copy is being generated by some other means).
  * @param isDownloadingCompleted True, if the local copy is fully available.
  * @param downloadOffset         Download will be started from this offset. downloadedPrefixSize is calculated from this offset.
  * @param downloadedPrefixSize   If isDownloadingCompleted is false, then only some prefix of the file starting from downloadOffset is ready to be read. downloadedPrefixSize is the size of that prefix.
  * @param downloadedSize         Total downloaded file bytes. Should be used only for calculating download progress. The actual file size may be bigger, and some parts of it may contain garbage.
  */
final case class LocalFile(
  path: String,
  canBeDownloaded: Boolean,
  canBeDeleted: Boolean,
  isDownloadingActive: Boolean,
  isDownloadingCompleted: Boolean,
  downloadOffset: Int,
  downloadedPrefixSize: Int,
  downloadedSize: Int
)

private[api] object LocalFile {
  def fromJava(o: TdApi.LocalFile): LocalFile =
    LocalFile(
      o.path,
      o.canBeDownloaded,
      o.canBeDeleted,
      o.isDownloadingActive,
      o.isDownloadingCompleted,
      o.downloadOffset,
      o.downloadedPrefixSize,
      o.downloadedSize
    )
}
